type IU = "Iue";
type Upper = Uppercase<IU>;
// type Upper = "IUE"
type Lower = Lowercase<IU>;
// type Lower = "iue"
type Capital = Capitalize<IU>;
// type Capital = "Iue"
type Uncaptial = Uncapitalize<IU>;
// type Uncaptial = "iue", 첫글자 소문자